apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
        - name: guestbook-app
          image: us-central1-docker.pkg.dev/gdcedge/gdcc-course/guestbook-gcp-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password5432@127.0.0.1:5432/mydb"
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.14
          command: ["/cloud_sql_proxy"]
          args:
            [
              "-instances=gdcedge:us-central1:guestbook-db=tcp:5432",
              "-credential_file=/secrets/cloudsql/credentials.json"
            ]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
---

apiVersion: v1
kind: Service
metadata:
  name: guestbook-app
spec:
  selector:
    app: guestbook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
