apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS guestbook_message (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      message VARCHAR(500) NOT NULL
    );

    INSERT INTO guestbook_message (name, message)
    VALUES
      ('Alice', 'Hello from the LinkedIn Learning!'),
      ('Bob', 'This is a great app!');

