apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
        - name: guestbook-app
          image: us-central1-docker.pkg.dev/gdcedge/gdcc-course/guestbook-app-slim:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres-service:5432/mydb"   # For GDCC
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-app
spec:
  selector:
    app: guestbook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
